const bool FONT_LOOKUP[][100] = {
    // A
    {false, false, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, false, true, false, false, false, false, true, false, false, true, false, false, false, false, true, false, false, true, false, false, false, false, true, true, false, true, false, false, false, false, false, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true},
    // B
    {true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true, false, true, false, true, true, true, true, true, false, true, false, true, true, true, true, true, false, true, false, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
    // C
    {false, true, true, true, true, true, true, false, true, true, false, false, false, false, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, true, false, false, false, false, true, true, false, false, true, true, true, true, true, false},
    // D
    {true, true, true, true, true, true, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, true, true, true, true, true, false, true, true, true, true, true, true, false},
    // E
    {true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true, false, true, false, true, true, true, true, true, false, true, false, true, true, true, true, true, false, true, false, true, true, true, true, true, false, true, false, true, true, true, true, true, false, true, false, true, true, true, true, true, true, true, true, true, true, true},
    // F
    {true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, true, true, true, true, true, true},
    // G
    {false, true, true, true, true, true, true, false, true, true, false, false, false, false, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, true, false, true, true, false, false, false, false, true, false, true, true, true, false, false, false, false, true, true, false, true, true, true, true, true, true, true, false, false, true, true, true, true, true, false},
    // H
    {true, true, true, true, true, true, true, true, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, true, true, true, true, true, true, true, true},
    // I
    {true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true},
    // J
    {false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, true, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
    // K
    {true, true, true, true, true, true, true, true, false, false, false, true, true, false, false, false, false, false, true, false, false, true, false, false, false, true, false, false, false, false, true, false, true, false, false, false, false, false, false, true, true, true, false, false, false, false, true, true, true, true, true, false, false, true, true, true, true, true, true, true, true, true, true, true},
    // L
    {true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true},
    // M
    {true, true, true, true, true, true, true, true, false, true, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, true, true, false, false, false, false, true, true, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
    // N
    {true, true, true, true, true, true, true, true, false, true, true, true, false, false, false, false, false, false, true, true, true, false, false, false, false, false, false, true, true, true, false, false, false, false, false, false, false, true, true, true, false, false, false, false, false, false, false, true, true, true, false, false, false, false, false, false, true, true, true, true, true, true, true, true},
    // O
    {false, true, true, true, true, true, true, false, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, false, true, true, true, true, true, true, false},
    // P
    {true, true, true, true, true, true, true, true, true, true, false, true, false, false, false, false, true, true, false, true, false, false, false, false, true, true, false, true, false, false, false, false, true, true, false, true, false, false, false, false, true, true, true, true, false, false, false, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false},
    // Q
    {false, true, true, true, true, true, true, false, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, true, false, true, true, true, true, false, false, false, true, true, true, true, true, false, false, false, false, true, true, false, true, true, true, true, true, true, true, false, false, false, false, false, false, true, true},
    // R
    {true, true, true, true, true, true, true, true, true, true, false, true, true, false, false, false, true, true, false, true, false, true, false, false, true, true, false, true, false, false, true, false, true, true, false, true, false, false, false, true, true, true, true, true, false, false, false, false, true, true, true, false, false, false, false, false, true, true, false, false, false, false, false, false},
    // S
    {false, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, false, false, false, false, false, true, true, true, false, false, false, false, false, true, true, true, false, false, false, false, false, true, true, true, false, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, true, true, true, true, true, false},
    // T
    {true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false},
    // U
    {true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
    // V
    {true, true, true, true, true, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, true, true, true, true, true, true, false, false},
    // W
    {true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, false, false, false, false, false, false, false, true, true, false, false, false, true, true, false, false, false, false, false, false, false, false, true, true, false, false, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
    // X
    {true, true, false, false, false, false, true, true, false, true, true, false, false, true, true, false, false, false, true, true, true, true, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, true, true, true, true, false, false, false, true, true, false, false, true, true, false, true, true, false, false, false, false, true, true},
    // Y
    {true, true, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, true, true, true, true, true, true, false, true, true, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
    // Z
    {true, true, false, false, false, false, true, true, true, false, true, false, false, false, true, true, true, false, false, true, false, false, true, true, true, false, false, false, true, false, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
    // 0
    {false, true, true, true, true, true, true, false, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false},
    // 1
    {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
    // 2
    {true, true, false, false, false, false, true, true, true, false, true, false, false, false, true, true, true, false, false, true, false, false, true, true, true, false, false, false, true, false, true, true, true, false, false, false, false, true, true, true, true, true, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
    // 3
    {true, false, false, false, false, false, true, false, true, false, false, false, false, false, true, true, true, false, false, false, false, false, true, true, true, false, true, false, true, false, true, true, true, true, false, true, false, true, true, true, false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
    // 4
    {false, false, true, true, true, true, true, true, false, false, false, false, true, false, false, false, false, false, false, true, true, false, false, false, false, true, true, false, true, false, false, false, true, true, false, false, true, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false},
    // 5
    {true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
    // 6
    {false, true, true, true, true, true, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
    // 7
    {true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, true, true, false, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
    // 8
    {false, true, true, true, true, true, true, false, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, false, true, true, true, true, true, true, false, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false},
    // 9
    {false, true, true, true, true, true, true, false, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, false, true, true, true, true, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false},
    // !
    {false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true},
    // /
    {false, false, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false},
    // \ (backslash)
    {true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true},
    // ,
    {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, true},
    // .
    {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false},
    // *
    {false, true, false, true, false, true, false, false, true, true, true, true, true, true, false, false, false, true, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
    // @
    {false, true, true, true, true, true, true, false, true, true, false, false, false, false, true, true, true, true, false, true, true, false, true, true, true, true, false, true, false, true, true, true, true, true, false, true, false, true, true, true, true, true, false, false, true, false, true, true, false, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false},
    // ?
    {false, true, true, true, true, true, true, false, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, false, false, false, false, true, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true},
    // £
    {false, true, true, true, true, true, true, false, true, true, false, true, false, true, true, true, true, true, false, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true, false, true, false, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false},
    // $
    {false, false, true, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, false, true, false, false, true, true, false, true, true, true, true, true, true, false, true, true, false, true, false, true, true, true, true, true, true, true, true, true, true, false, false, false, true, false, false, true, false, false, false, false, false, false, false, false, false, false}
};
